version: "3.9"

services:
  app:
    image: ${IMAGE_NAME}
    container_name: ecr-financy-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_POSTGRES_HOST=${POSTGRES_HOST}
      - APP_POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - APP_POSTGRES_DATABASE=${POSTGRES_DB}
      - APP_POSTGRES_USERNAME=${POSTGRES_USER}
      - APP_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - APP_JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
    networks:
      - ecr-network

networks:
  ecr-network:
    external: true
