"""create credit_card_transactions table

Revision ID: 052a9807d734
Revises: 7e1fa6636c7a
Create Date: 2025-12-22 11:01:09.728212
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '052a9807d734'
down_revision: Union[str, None] = '7e1fa6636c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fine', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('category_id', sa.Text(), nullable=True),
    sa.Column('subcategory_id', sa.Text(), nullable=True),
    sa.Column('cost_center_id', sa.Text(), nullable=True),
    sa.Column('contact_id', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('account', sa.Text(), nullable=True),
    sa.Column('recurrence', sa.Boolean(), nullable=True),
    sa.Column('competence', sa.Text(), nullable=True),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card_transactions')
    # ### end Alembic commands ###

