"""add_ofx_transactions_table

Revision ID: 07a21826f270
Revises: 55eb34dae55c
Create Date: 2026-03-07 11:36:23.508145
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '07a21826f270'
down_revision: Union[str, None] = '55eb34dae55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofx_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fitid', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('bank_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ofx_transactions_fitid'), 'ofx_transactions', ['fitid'], unique=True)
    op.create_index(op.f('ix_ofx_transactions_id'), 'ofx_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ofx_transactions_id'), table_name='ofx_transactions')
    op.drop_index(op.f('ix_ofx_transactions_fitid'), table_name='ofx_transactions')
    op.drop_table('ofx_transactions')
    # ### end Alembic commands ###

