"""reconciliation_2

Revision ID: 11b6ebb64bea
Revises: 07a21826f270
Create Date: 2026-03-07 15:47:30.366890
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '11b6ebb64bea'
down_revision: Union[str, None] = '07a21826f270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('reconciled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('expenses', sa.Column('reconciliation_date', sa.Date(), nullable=True))
    op.add_column('expenses', sa.Column('reconciled_by', sa.Text(), nullable=True))
    op.add_column('incomes', sa.Column('reconciled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('incomes', sa.Column('reconciliation_date', sa.Date(), nullable=True))
    op.add_column('incomes', sa.Column('reconciled_by', sa.Text(), nullable=True))
    op.add_column('ofx_transactions', sa.Column('reconciled', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('ofx_transactions', sa.Column('reconciliation_date', sa.Date(), nullable=True))
    op.add_column('ofx_transactions', sa.Column('reconciled_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ofx_transactions', 'reconciled_by')
    op.drop_column('ofx_transactions', 'reconciliation_date')
    op.drop_column('ofx_transactions', 'reconciled')
    op.drop_column('incomes', 'reconciled_by')
    op.drop_column('incomes', 'reconciliation_date')
    op.drop_column('incomes', 'reconciled')
    op.drop_column('expenses', 'reconciled_by')
    op.drop_column('expenses', 'reconciliation_date')
    op.drop_column('expenses', 'reconciled')
    # ### end Alembic commands ###

