"""add active to ofx_transaction

Revision ID: 202603150001
Revises: 9ec783343164
Create Date: 2026-03-15 10:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202603150001'
down_revision: Union[str, None] = '9ec783343164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ofx_transactions', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ofx_transactions', 'active')
    # ### end Alembic commands ###
