"""create reconciliations table

Revision ID: 44d07754cb78
Revises: 11b6ebb64bea
Create Date: 2026-03-08 13:29:34.163692
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '44d07754cb78'
down_revision: Union[str, None] = '11b6ebb64bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ofx_transaction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('reconciled_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ofx_transaction_id'], ['ofx_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_id'), 'reconciliations', ['id'], unique=False)
    op.alter_column('ofx_transactions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ofx_transactions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_reconciliations_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    # ### end Alembic commands ###

