"""transfer_id

Revision ID: 55eb34dae55c
Revises: c0b3ebf4ea7b
Create Date: 2026-03-06 21:36:24.226913
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '55eb34dae55c'
down_revision: Union[str, None] = 'c0b3ebf4ea7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('transfer_id', sa.UUID(), nullable=True))
    op.add_column('incomes', sa.Column('transfer_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'transfer_id')
    op.drop_column('expenses', 'transfer_id')
    # ### end Alembic commands ###

