"""add_closing_and_due_day_to_accounts

Revision ID: 59a75830aba8
Revises: 052a9807d734
Create Date: 2025-12-22 18:00:23.174862
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '59a75830aba8'
down_revision: Union[str, None] = '052a9807d734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('closing_day', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'due_day')
    op.drop_column('accounts', 'closing_day')
    # ### end Alembic commands ###

