"""invoices

Revision ID: af07ab63cb02
Revises: 7be519642bb1
Create Date: 2025-12-27 15:30:06.434312
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "af07ab63cb02"
down_revision: str | None = "7be519642bb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("credit_card_invoices", sa.Column("expense_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credit_card_invoices", "expense_id")
    # ### end Alembic commands ###
