"""remove original_amount and recurrence columns

Revision ID: c0b3ebf4ea7b
Revises: d1669212865f
Create Date: 2026-03-03 01:06:34.727652
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'c0b3ebf4ea7b'
down_revision: Union[str, None] = 'd1669212865f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_transactions', 'original_amount')
    op.drop_column('credit_card_transactions', 'recurrence')
    op.drop_column('expenses', 'original_amount')
    op.drop_column('expenses', 'recurrence')
    op.drop_column('incomes', 'original_amount')
    op.drop_column('incomes', 'recurrence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('recurrence', sa.Boolean(), nullable=True))
    op.add_column('incomes', sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('recurrence', sa.Boolean(), nullable=True))
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('credit_card_transactions', sa.Column('recurrence', sa.Boolean(), nullable=True))
    op.add_column('credit_card_transactions', sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###
