"""add_payment_fields_to_credit_card_invoices

Revision ID: e3cdcde546b4
Revises: af07ab63cb02
Create Date: 2026-01-16 00:08:43.160535
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'e3cdcde546b4'
down_revision: Union[str, None] = 'af07ab63cb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card_invoices', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('credit_card_invoices', sa.Column('interest', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('credit_card_invoices', sa.Column('fine', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('credit_card_invoices', sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('credit_card_invoices', sa.Column('total_paid', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card_invoices', 'total_paid')
    op.drop_column('credit_card_invoices', 'discount')
    op.drop_column('credit_card_invoices', 'fine')
    op.drop_column('credit_card_invoices', 'interest')
    op.drop_column('credit_card_invoices', 'payment_date')
    # ### end Alembic commands ###

