"""create_credit_card_invoices_table

Revision ID: ff50dc2fd63a
Revises: 59a75830aba8
Create Date: 2025-12-26 19:40:01.774964
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ff50dc2fd63a'
down_revision: Union[str, None] = '59a75830aba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

