name: Deploy to Cloud Run - Staging

on:
  push:
    branches:
      - staging
env:
  REGION: europe-west1
  PROJECT_ID: spry-metric-460820-i8
  SERVICE: ecr-financy-back


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "beta"
      
      - name: Build and Push Container
        run: |-
          gcloud auth configure-docker
          docker build -t "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" .
          docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          install_components: "beta"
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

          env_vars: |-
            APP_postgres_host=/cloudsql/spry-metric-460820-i8:us-central1:ecr-financy-back
            APP_postgres_database=financy_db
            APP_postgres_password=hX_y9cV6Oe=SGu{m
            APP_postgres_port=5432
            APP_postgres_username=postgres
